Whole M-PARTY refactoring and optimization(#3)
* Start complete code refactoring

* variable names correction; remove commented code; reduce CC

* Refactor the parse_fasta function; changed the way that the arguments are read into the config file

* CLI arguments declaration now have its own file, to improve main script readability

* [REFACTOR] start table and text report functions refactoring

* [REFACTOR] clean except clauses; remove useless code; rewrite config writing and reading

* [REFACTOR] Start cleaning all the mess from the pathing

* [REFACTOR] Move text report text writing to its own file

* [FIX] Further cleaning and small bug fix

* [REFACTOR] The goal here is to save the variables used by the text as they are made available throughout the pipeline

* Text cleaning and code refactor

* Added docs; removed commented code

* [REFACTOR] Start rearranging the way pathing is done, dirs are created and removed

* [REMOVE] commented code

* [UPDATE] gitignore

* [UPDATE] gitignore for mparty results folders

* [REFACTOR] major changes to main pipeline and side util funcs

* [REFACTOR] more changes

* [UPDATE] github actions

* [FIX] artifact version

* [REFACTOR] start to change args checks to its single function

* [REFACTOR] major changes to the database construction workflow part of the pipeline

* [REFACTOR] condense database construction pipeline

* [TEST] quick update to test m-party CI version

* [DOCS] a lit bit of documentation

* [FIX] quick fix

* fix actions

* another fix

* [TEST] keep testing actions

* [ADD] disable to tqdm when verbose is False

* [FIX] fiinal try

* [FIX] another try to checkout to refactor

* ahhhhhh

* try checkout in dockefile

* another one

* [FIX] possible module names clash

* try to see the probem with the modules import

* hello

* [FIX] modules pathing

* [ADD] job for data cleaning

* debug actions

* [FIX] config folder not present

* 1

* [UPDATE] start testing the overall path refactoring

* [REFACTOR] change all hardcoded paths to the PathManager class variables

* [FIX] quick path fix in shutil

* [FIX] fix in a filename

* [FIX] please work actions

* [FIX] actions "clean" run accepts failure

* [FIX] paths

* [ADD] add more paths to the PathManager, and change all hardcoded paths in the mainpipeline

* [FIX] paths in concat hmm code

* [FIX] error not building the hmms

* try again

* [FIX] bad escape characters and paths

* [FIX] escape characters and paths, docker file and actions updated

* [CHANGE] actions first determines the event that triggered it

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,34 +2,73 @@ name: CI
 
 on:
   push:
-    branches: [ main ]
+    branches:
+      - main
+      - refactor
   pull_request:
-    branches: [ main ]
+    branches:
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
+
+      - name: Determine the branch name
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            echo "GIT_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+          else
+            echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
+          fi
 
       - name: Build and push
-        uses: docker/build-push-action@v2
+        uses: docker/build-push-action@v6
         with:
           context: .
           file: ./Dockerfile
           tags: mparty:latest
+          build-args: GIT_BRANCH=${{ env.GIT_BRANCH }}  # Pass branch name dynamically
           outputs: type=docker, dest=/tmp/mparty.tar
 
       - name: Upload artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: mparty
           path: /tmp/mparty.tar
+
+  version:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: mparty
+          path: /tmp
+
+      - name: Load Docker image
+        run: |
+          docker load --input /tmp/mparty.tar
+          docker image ls -a
+
+      - name: Check base entrypoint
+        run: docker run mparty bin/bash -c "ls /opt/conda/bin"
+
+      - name: Print main script contents
+        run: docker run mparty bin/bash -c "cat /opt/conda/bin/m-party.py"
+      
+      - name: Check m-party version
+        run: docker run mparty bin/bash -c "m-party.py --version"
 
   annotation:
     runs-on: ubuntu-latest
@@ -39,7 +78,7 @@ jobs:
         uses: docker/setup-buildx-action@v1
 
       - name: Download artifact
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4
         with:
           name: mparty
           path: /tmp
@@ -59,7 +98,7 @@ jobs:
         run: docker run mparty bin/bash -c "cd "
 
       - name: Annotation workflow by FASTA input, report text creation and excel table format
-        run: docker run mparty bin/bash -c "m-party.py -i M-PARTY/ci/positive_control.fasta --kegg K21104 -w both --hmm_db_name KEGG_test_both --verbose -o Testing_KEGG_positive --output_type excel -rt"
+        run: docker run mparty bin/bash -c "m-party.py -i M-PARTY/ci/positive_control.fasta --kegg K21104 -w both --hmm_db_name KEGG_test_both -o Testing_KEGG_positive --output_type excel"
 
       - name: Annotation workflow with gut metagenome proteins (negative dataset), generate same outputs
         run: docker run mparty bin/bash -c "m-party.py -i M-PARTY/ci/gut_metagenome_proteins.fasta -it metagenome --kegg K21104 -w both --hmm_db_name KEGG_test_both --verbose -o Testing_KEGG_positive --output_type excel -rt"
@@ -156,7 +195,7 @@ jobs:
         uses: docker/setup-buildx-action@v1
 
       - name: Download artifact
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v4
         with:
           name: mparty
           path: /tmp
@@ -172,9 +211,6 @@ jobs:
       - name: Print M-PARTY's main script
         run: docker run mparty bin/bash -c "m-party.py -h"
 
-      - name: Database construction workflow with small FASTA protein file
-        run: docker run mparty bin/bash -c "m-party.py -w database_construction --hmm_db_name protein_file_inputest --input_seqs_db_const M-PARTY/ci/KEGG_nuc_test.fasta --input_type_db_const nucleic -t 8 --verbose"
-      
       - name: Database construction workflowfor with KEGG KO
         run: docker run mparty bin/bash -c "m-party.py -w database_construction --hmm_db_name test_KEGG_KO --kegg K21104 --verbose"
       
@@ -186,3 +222,39 @@ jobs:
 
       - name: Database construction workflowfor with InterPro individual protein IDs
         run: docker run mparty bin/bash -c "m-party.py -w database_construction --hmm_db_name test_KEGG_Prots --interpro A0A000 A0A001 A0A002 --verbose"
+      
+      - name: Database construction workflow with small FASTA protein file
+        run: docker run mparty bin/bash -c "m-party.py -w database_construction --hmm_db_name protein_file_inputest --input_seqs_db_const M-PARTY/ci/KEGG_nuc_test.fasta --input_type_db_const nucleic -t 8 --verbose"
+      
+  clean:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: mparty
+          path: /tmp
+
+      - name: Load Docker image
+        run: |
+          docker load --input /tmp/mparty.tar
+          docker image ls -a
+
+      - name: Simpler database construction pipeline
+        run: docker run mparty bin/bash -c "m-party.py -w database_construction --kegg K21104 --hmm_db_name PET_hydrolase"
+      
+      - name: Check error raise for clean data
+        run: |
+          if docker run mparty bin/bash -c "m-party.py --clean"; then
+            echo "Error: Command was expected to fail but it succeeded."
+            exit 1
+          else
+            echo "Success: Command failed as expected."
+          fi
+
+      - name: Clean data
+        run: docker run mparty bin/bash -c "m-party.py --clean --hmm_db_name PET_hydrolase"
